### ISSUE TITLE
Too difficult to recognize the number

### ISSUE THREAD

**Issue by horsley** [dchest/captcha#11]
great work!
But numbers stay too close and sometimes overlap.
Do you have an image size / ratio recommendation or design an param to set the difficulty?

**Comment by dchest** [comment]
Thanks! Defaults look pretty good to me (like [here](https://github.com/dchest/captcha#examples)). The numbers are overlapping by design, as this makes it harder for computers to recognize numbers. I suggest including reload button for some edge cases when it's hard to read numbers.

**Comment by alexzorin** [comment]
@dchest would you consider exporting `maxSkew`? It may be helpful to users of this package to be able to make their own decision regarding the difficulty trade-off. `0.7` is quite extreme, at times.

**Comment by dchest** [comment]
@alexzorin I wouldn't mind a pull request which introduces something like:

```go
func SetDifficulty(d DifficultyLevel)
func Difficulty() DifficultyLevel
```

where `DifficultyLevel` is an `int` type and `Easy`, `Normal`, `Hard` constants.

Then image (and maybe audio) functions would adjust parameters based on the difficulty, e.g. it could set maxSkew to something less for `Easy` mode.

(Of course, it would be better if those could be configured not globally for the package, but there was a way to create an instance of captcha-generator, but this is for 2.0, since we already have `SetCustomStore`...)

**Comment by ustcwudi** [comment]
> Thanks for the response!
> 
> > `DifficultyLevel`
> 
> I can appreciate if you would like to avoid exposing specific levers. I had a go writing this PR, but it became apparent that this approach wouldn't really meet my own needs (as I'm making a fairly "arbitrary" set of adjustments). Perhaps in this case we're happy to just vendor our changes. Thanks for the cool project!

you can modify the maxSkew

// Maximum absolute skew factor of a single digit.
maxSkew = 0.7
