### ISSUE TITLE
Security issue: Can't set custom security headers

### ISSUE THREAD

**Issue by iu4u57k3** [dchest/captcha#22]
We can setup a captcha server by using:
`http.Handle("/captcha/", captcha.Server(captcha.StdWidth, captcha.StdHeight)`

However, this does not allow setting custom headers for enhancing security such as:
```
Access-Control-Allow-Origin
X-Frame-Options
X-Content-Type-Options
X-XSS-Protection
```
This leaves the application vulnerable to various attacks

**Comment by dchest** [comment]
`Server` is the standard Go `http.Handler`, so you can combine it with other `http.Handler` or `http.HandlerFunc` to set headers before calling it. For example,

```
	captchaServer := captcha.Server(captcha.StdWidth, captcha.StdHeight)

	http.HandleFunc("/captcha/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-My-Header", "itworks")
		captchaServer.ServeHTTP(w, r)
	})
```

Most of the headers you listed seem useless, though:

* `X-Content-Type-Options: nosniff`: what the attack is? Server serves image and audio captchas, there's no way to make it serve user-provided data, so content type sniffing won't lead to attacks.
* `X-XSS-Protection`: again, no HTML/JS is served, so there's no XSS to protect against.
* `X-Frame-Options` seems the most useful one, however, again useless, since images and audio don't need frames to be able to be embedded into other origins.
* `Access-Control-Allow-Origin` is not a header that restricts behavior, it relaxes default browser restrictions: for images, it can be used to *enable* cross-origin manipulation of captchas with canvas, which is not what you want.

Anything I missed?

**Comment by iu4u57k3** [comment]
Thanks for your clarification!

**Comment by iu4u57k3** [comment]
It will be a good idea to add `w.Header().Set("X-Frame-Options", "DENY")` in  `captcha.serve` function.
So there will be no need to add custom headers.

**Comment by dchest** [comment]
`Serve` serves images and audio, so `X-Frame-Options` is useless for it as mentioned above.
